baseURL = 'https://ellatalk.top/'
title = 'EllaTalk'
theme = "dream"


defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

[languages]

[languages.zh]
  languageName = "中文"
  weight = 1
  contentDir = "content/zh"
  languageCode = "zh"
  title = "EllaTalk 中文"

  [[languages.zh.menu.main]]
    name = "分类"
    url = "/zh/categories/"
    weight = 1

  [[languages.zh.menu.main]]
    name = "标签"
    url = "/zh/tags/"
    weight = 2

[languages.en]
  languageName = "English"
  weight = 2
  contentDir = "content/en"
  languageCode = "en"
  title = "EllaTalk English"

  [[languages.en.menu.main]]
    name = "Categories"
    url = "/en/categories/"
    weight = 1

  [[languages.en.menu.main]]
    name = "Tags"
    url = "/en/tags/"
    weight = 2


[services]
[services.googleAnalytics]
ID = "..."

[services.disqus]
shortname = "..."

[params]
lightTheme = "emerald"
darkTheme = "forest"
# backgroundImage = "images/global-background.jpg" 
avatar = "/img/avatar.jpg"
author = "EllaSang"
description = "EllaSang 的个人博客～"

headerTitle = "EllaSang's Blog"
motto = "Beautiful things don't ask for attention!"

rss = true
# utterancesRepo = "g1eny0ung/g1eny0ung.github.io"
email = "ella.best.asimov@gmail.com"
siteStartYear = 2025
favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = true
reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
reorderShares = ["x", "facebook", "whatsapp"]

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"